FROM golang:1.22-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o server .

FROM alpine:3.20

RUN apk add --no-cache g++ libstdc++ ca-certificates && update-ca-certificates

WORKDIR /app
COPY --from=builder /app/server /app/server

EXPOSE 10000
CMD ["/app/server"]
